name: Dredd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest    
    container: pbui/cse-30341-fa20-project01
    steps:
    - uses: actions/checkout@v2

    - name: Testing
      run:  make test
